apiVersion: v1
kind: Service
metadata:
  name: signalflow
  namespace: signalflow
  labels:
    app.kubernetes.io/name: signalflow
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: signalflow
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
