{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signalflow.postgresFullname" . }}
  labels:
    {{- include "signalflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
{{- end }}
