apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signalflow.fullname" . }}
  labels:
    {{- include "signalflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "signalflow.databaseURL" . | quote }}
  {{- range $key, $value := .Values.secrets }}
  {{- if ne $key "DATABASE_URL" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
